/*
 * Copyright (c) 2017 - 2022, Dell Technologies, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#pragma once
#include <schannel.h>
#include <Winhttp.h>
#include "generic_defs.h"
#include "S3Error.h"
#include "ThreadPool.h"
#include "SimpleWorkerThread.h"
#include "CRWLock.h"
#include "Logging.h"
#include "fmtnum.h"


namespace ecs_sdk
{


const UINT GDReadWriteChunkMax = 0x100000;			// maxiumum read/write request size
const UINT MaxRetryCount = 5;
const UINT MaxWriteRequest = 0;
const UINT MaxWriteRequestThrottle = 8192;
const UINT MaxS3DeleteObjects = 1000;				// maximum number of objects to delete in one command (S3)
const UINT DefaultMaxStreamQueueSizeRecv = 1024;	// maximum size of stream queue. if there is a mismatch between the queue feed and consumer, you don't want it to grow too big
const UINT DefaultS3AuthV4ChunkSize = 0x200000;		// default chunk size when using v4 auth. this ends up being the buffer size when streaming writes


// ECS x-emc-mtime header shows the time as a number
// it is like a Unix time_t except it is in millisec resolution
// convert to UTC FILETIME
inline FILETIME ECSmtimeToFileTime(ULONGLONG mtime)
{
	FILETIME ftTime;
	ULONGLONG ull = (mtime * 10000ULL) + 116444736000000000ULL;
	ftTime.dwLowDateTime = (DWORD)ull;
	ftTime.dwHighDateTime = ull >> 32;
	return ftTime;
}

class CInternetHandle
{
private:
	HINTERNET hInternet;

public:
	CInternetHandle(HINTERNET hInit = nullptr)
	{
		hInternet = hInit;
	}

	~CInternetHandle()
	{
		(void)CloseHandle();
		hInternet = nullptr;
	}

	CInternetHandle &operator =(HINTERNET hParam)
	{
		if (hInternet != nullptr)
			(void)CloseHandle();
		hInternet = hParam;
		return *this;
	}

	const CInternetHandle& operator =(const CInternetHandle& src)
	{
		if (&src == this)
			return(*this);
		hInternet = nullptr;				// for an assignment, don't bother assigning the handle, it really shouldn't be duplicated
		return *this;
	};

	CInternetHandle(const CInternetHandle &src)
	{
		(void)src;
		hInternet = nullptr;				// for an assignment, don't bother assigning the handle, it really shouldn't be duplicated
	}

	operator HINTERNET() const
	{
		return hInternet;					//lint !e1535 !e1536 !e1537 : member function 'CInternetHandle::operator void *' exposes lower access pointer member 'CInternetHandle::hInternet'
	}

	DWORD CloseHandle()
	{
		DWORD dwError = ERROR_SUCCESS;
		if (IfOpen())
		{
			if (!WinHttpCloseHandle(hInternet))
			{
				dwError = GetLastError();
				if (dwError != ERROR_INVALID_HANDLE)
					LogMessage(TEXT(__FILE__), __LINE__, _T("WinHttpCloseHandle error"), dwError);
			}
			hInternet = nullptr;
		}
		return dwError;
	}

	bool IfOpen() const
	{
		return hInternet != nullptr;
	}
};

class ECSUTIL_EXT_CLASS CECSConnection
{
public:
	struct ECS_BILLING_BUCKET_TAG
	{
		CString sTagKey;
		CString sTagValue;
	};

	// bucket info for bucket - ECSAdminBucketInfo()
	struct ECS_BUCKET_INFO
	{
		CString name;										// assigned to this resource in ECS.The resource name is set by a userand can be changed at any time.It is not a unique identifier
		CString id;											// Identifier that is generated by ECS when the resource is created.The resource Id is guaranteed to be uniqueand immutable across all virtual data centers for all time.
		CString link;										// Hyperlink to the details for this resource
		FILETIME created = { 0,0 };							// Bucket creation time
		INT softquota = 0ULL;								// Bucket soft quota in GB (-1 if no soft quota)
		bool fs_access_enabled = false;						// Bucket "file system access enabled" status
		bool locked = false;								// "Locked" status of a bucket
		CString vpool;										// Replication group id
		CString name_space;									// Namespace
		CString owner;										// Bucket owner
		bool is_stale_allowed = false;						// Bucket isStaleAllowed flag
		bool is_tso_read_only = false;						// Bucket isStaleAllowed flag
		bool is_object_lock_enabled = false;				// Bucket isObjectLockEnabled flag
		bool default_object_lock_retention_mode = false;	// Bucket default_object_lock_retention_mode flag
		UINT default_object_lock_retention_years = 0;		// Default object lock retention years
		UINT default_object_lock_retention_days = 0;		// Default object lock retention days
		bool is_encryption_enabled = false;					// D@RE Bucket isEncryptionEnabled flag
		UINT default_retention = 0;							// Default bucket retention
		INT block_size = 0;									// hard quota in GB  (-1 if no hard quota)
		UINT auto_commit_period = 0;						// auto - commit interval
		INT notification_size = 0;							// Notification size (soft quota?) in GB  (-1 if no notification)
		CString api_type;									// API type
		UINT retention = 0;									// Default retention value for the bucket.
		bool default_group_file_read_permission = false;	// Flag indicating the Read permission for default group
		bool default_group_file_write_permission = false;	// Flag indicating the file write permission for default group
		bool default_group_file_execute_permission = false;	// Flag indicating the file execute permission for default group
		bool default_group_dir_read_permission = false;		// Flag indicating the directory read permission for default group.This is only applicable to folders created within the Filesystem - Enabled bucket.It is not applicable to files / objects
		bool default_group_dir_write_permission = false;	// Flag indicating the directory write permission for default group.This is only applicable to folders created within the Filesystem - Enabled bucket.It is not applicable to files / objects
		bool default_group_dir_execute_permission = false;	// Flag indicating the directory execute permission for default group.This is only applicable to folders created within the Filesystem - Enabled bucket.It is not applicable to files / objects
		CString default_group;								// Bucket's default group
		CString datatype;									// The meta key data type.
		bool isEnabled = false;								// Getter for the enabled flag.
		bool mdTokens = false;								// Getter for the mdTokens flag.
		UINT maxKeys = 0;									// Getter for maxKeys.
		INT blockSizeInCount = 0;
		INT notificationSizeInCount = 0;
		INT audit_delete_expiration = 0;
	};

	// capacity info for VDC - ECSAdminCapacity()
	struct ECS_CAPACITY
	{
		ULONGLONG ullTotalProvisioned_GB = 0ULL;	// total storage available
		ULONGLONG ullTotalFree_GB = 0ULL;			// free space
	};

	// Billing info for Namespace/bucket - ECSAdminBillingBucket()
	struct ECS_BILLING_BUCKET
	{
		CString sBucket;							// bucket name
		CString sNamespace;							// namespace name
		CString sVpoolID;							// Replication group
		double dTotalSize = 0;						// total size in bytes
		ULONGLONG ullTotalObjects = 0ULL;			// total number of objects
		double dTotalSizeDeleted = 0;				// total size in bytes
		ULONGLONG ullTotalObjectsDeleted = 0ULL;	// total number of objects
		FILETIME ftSampleTime = { 0,0 };			// Time at which these data collected
		FILETIME ftUpToDateTill = { 0,0 };			// Time till which the data is consistent.This has an unexpected value during data reconstruction.
		std::list<ECS_BILLING_BUCKET_TAG> TagList;	// list of tags set for the Bucket
		double dTotalMPUSize = 0;					// Total MPU size
		ULONG ulTotalMPUParts = 0;					// Total MPU parts
	};

	// used for DirListing context if calling it each time for the 
	class LISTING_NEXT_MARKER_CONTEXT
	{
	public:
		bool bTruncated;
		UINT dwMaxNum;						// maximum number of elements to request at a time
		CString sS3NextMarker;
		CString sS3NextKeyMarker;
		CString sS3NextVersionIdMarker;
	
		LISTING_NEXT_MARKER_CONTEXT(UINT dwMaxNumParam = 0)
			: bTruncated(false)
			, dwMaxNum(dwMaxNumParam)
		{}
		bool IsTruncated(void)
		{
			return bTruncated;
		}
		void Clear(void)
		{
			bTruncated = false;
			sS3NextMarker.Empty();
			sS3NextKeyMarker.Empty();
			sS3NextVersionIdMarker.Empty();
		}
	};

	// DT Query support
	struct DT_QUERY_RESPONSE
	{
		bool bStatus;
		ULONGLONG ullTotalDataSize;
		ULONGLONG ullShippedDataSize;
		UINT uShippedDataPercentage;
		std::list<CString> DataRangeShippingDetails;

		DT_QUERY_RESPONSE()
			: bStatus(false)
			, ullTotalDataSize(0ULL)
			, ullShippedDataSize(0ULL)
			, uShippedDataPercentage(0)
		{}
	};

	// metadata search
	enum class E_MD_SEARCH_TYPE : BYTE
	{
		Unknown,
		Integer,
		Datetime,
		Decimal,
		String
	};
	static E_MD_SEARCH_TYPE TranslateSearchFieldType(LPCWSTR pszType);
	static CString TranslateSearchFieldType(E_MD_SEARCH_TYPE Type);
	enum class E_MD_SEARCH_FIELD
	{
		Unknown,
		SYSMD,
		USERMD,
	};
	struct S3_METADATA_SEARCH_ENTRY
	{
		CString sName;
		E_MD_SEARCH_TYPE Type;
		S3_METADATA_SEARCH_ENTRY()
			: Type(E_MD_SEARCH_TYPE::Unknown)
		{}
		int Compare(const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return sName.Compare(rec.sName);
		}
		bool operator == (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) == 0;
		};
		bool operator != (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) != 0;
		};
		bool operator < (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) < 0;
		};
		bool operator <= (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) <= 0;
		};
		bool operator > (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) > 0;
		};
		bool operator >= (const S3_METADATA_SEARCH_ENTRY& rec) const
		{
			return Compare(rec) >= 0;
		};
	};

	struct S3_METADATA_SEARCH_FIELDS
	{
		std::list<S3_METADATA_SEARCH_ENTRY> KeyList;
		std::list<S3_METADATA_SEARCH_ENTRY> AttributeList;
	};

	struct S3_METADATA_SEARCH_FIELDS_BUCKET
	{
		bool bSearchEnabled;
		std::list<S3_METADATA_SEARCH_ENTRY> KeyList;
		S3_METADATA_SEARCH_FIELDS_BUCKET()
			: bSearchEnabled(false)
		{}
	};

	struct ECSUTIL_EXT_CLASS S3_METADATA_SEARCH_PARAMS
	{
		CString sBucket;
		CString sExpression;
		CString sAttributes;
		CString sSorted;
		bool bOlderVersions;
		S3_METADATA_SEARCH_PARAMS()
			: bOlderVersions(false)
		{}
		int Compare(const S3_METADATA_SEARCH_PARAMS& Rec) const;
		bool operator == (const S3_METADATA_SEARCH_PARAMS& Rec) const;
		bool operator != (const S3_METADATA_SEARCH_PARAMS& Rec) const;
		CString Format(void) const;
	};

	struct S3_METADATA_SEARCH_RESULT_MD_MAP
	{
		CString sKey;
		CString sValue;
	};

	struct S3_METADATA_SEARCH_RESULT_QUERY_MD
	{
		E_MD_SEARCH_FIELD FieldType;
		std::list<S3_METADATA_SEARCH_RESULT_MD_MAP> MDMapList;
		S3_METADATA_SEARCH_RESULT_QUERY_MD()
			: FieldType(E_MD_SEARCH_FIELD::Unknown)
		{}
	};

	struct S3_METADATA_SEARCH_RESULT_OBJECT_MATCH
	{
		CString sObjectName;
		CString sObjectId;
		CString sVersionId;
		std::list<S3_METADATA_SEARCH_RESULT_QUERY_MD> QueryMDList;
	};

	struct S3_METADATA_SEARCH_RESULT
	{
		CString sBucket;
		std::deque<S3_METADATA_SEARCH_RESULT_OBJECT_MATCH> ObjectMatchList;
	};

	struct S3_BUCKET_INDEX_ENTRY
	{
		CString sFieldName;				// either system metadata (ObjectName, Owner, ...) or user metadata (x-amz-meta-??)
		E_MD_SEARCH_TYPE Type;			// type: string, integer, decimal, datetime
		S3_BUCKET_INDEX_ENTRY()
			: Type(E_MD_SEARCH_TYPE::Unknown)
		{}
	};

	struct S3_BUCKET_OPTIONS
	{
		bool bEnableFS;										// file system enabled bucket
		bool bTempSiteOutage;								// allow access during TSO
		DWORD dwRetention;									// retention time in seconds
		std::list<S3_BUCKET_INDEX_ENTRY> IndexFieldList;			// fields to index to enable metadata search
		S3_BUCKET_OPTIONS()
			: bEnableFS(false)
			, bTempSiteOutage(true)
			, dwRetention(0)
		{}
	};

	struct ECSUTIL_EXT_CLASS S3_MPU_COMPLETE_INFO
	{
		CString sLocation;
		CString sBucket;
		CString sKey;
		CString sETag;
	};

	struct ECSUTIL_EXT_CLASS S3_ENDPOINT_INFO
	{
		std::list<CString> EndpointList;
		CString sVersion;
	};

	enum class E_OBJECT_LOCK_MODE : unsigned char
	{
		Unknown,
		Governance,
		Compliance,
	};

	struct ECSUTIL_EXT_CLASS S3_OBJ_LOCK_CONFIG
	{
		bool bObjLockEnabled = false;
		E_OBJECT_LOCK_MODE Mode = E_OBJECT_LOCK_MODE::Unknown;
		DWORD dwObjLockDays = 0;
		DWORD dwObjLockYears = 0;
	};

	struct ECSUTIL_EXT_CLASS S3_LIFECYCLE_RULE
	{
		CString sRuleID;									// user assigned rule ID
		CString sPath;										// optional subpath to apply rule (relative to bucket)
		bool bEnabled;										// enabled or disabled
		bool bExpiredDeleteMarkers;							// set: expired delete markers are deleted
		DWORD dwDays;										// number of days until expiration (current objects)
		DWORD dwNoncurrentDays;								// number of days (for non-current objects) until expiration
		DWORD dwAbortIncompleteMultipartUploadDays;			// number of days to abort incomplete uploads
		FILETIME ftDate;									// date of expiration (current objects)

		S3_LIFECYCLE_RULE()
			: bEnabled(false)
			, bExpiredDeleteMarkers(false)
			, dwDays(0)
			, dwNoncurrentDays(0)
			, dwAbortIncompleteMultipartUploadDays(0)
		{
			ZeroFT(ftDate);
		}
		void Empty(void)
		{
			sRuleID.Empty();
			sPath.Empty();
			bEnabled = false;
			bExpiredDeleteMarkers = false;
			dwDays = 0;
			dwNoncurrentDays = 0;
			dwAbortIncompleteMultipartUploadDays = 0;
			ZeroFT(ftDate);
		}
		bool IsEmpty(void)
		{
			return sRuleID.IsEmpty() || ((dwDays == 0) && (dwNoncurrentDays == 0) && IfFTZero(ftDate) && (bExpiredDeleteMarkers == 0));
		}
		bool operator < (const S3_LIFECYCLE_RULE& rec) const
		{
			return sRuleID.CompareNoCase(rec.sRuleID) < 0;
		}
	};

	struct ECSUTIL_EXT_CLASS S3_LIFECYCLE_INFO
	{
		std::list<S3_LIFECYCLE_RULE> LifecycleRules;			// list of lifecycle rules

		S3_LIFECYCLE_INFO()
		{}
	};

	struct ECSUTIL_EXT_CLASS S3_REPLICATION_INFO
	{
		bool bIndexReplicated;
		long double dReplicatedDataPercentage;

		S3_REPLICATION_INFO()
			: bIndexReplicated(false)
			, dReplicatedDataPercentage(0.0)
		{}
	};

	struct ECSUTIL_EXT_CLASS S3_ADMIN_USER_INFO
	{
		CString sUser;
		CString sNamespace;
		CString sSecret;
		CString sTags;
		CString sLink;
		FILETIME ftKeyCreate;
		FILETIME ftKeyExpiry;
		S3_ADMIN_USER_INFO()
		{
			ZeroFT(ftKeyCreate);
			ZeroFT(ftKeyExpiry);
		}
		bool IsEmpty(void)
		{
			return sUser.IsEmpty();
		}
		void EmptyRec(void)
		{
			sUser.Empty();
			sNamespace.Empty();
			sSecret.Empty();
			sTags.Empty();
			sLink.Empty();
			ZeroFT(ftKeyCreate);
			ZeroFT(ftKeyExpiry);
		}
	};

	struct ECSUTIL_EXT_CLASS S3_ADMIN_USER_KEY_INFO
	{
		CString sSecret1;
		CString sSecret2;
		CString sLink;
		FILETIME ftKeyCreate1;
		FILETIME ftKeyExpiry1;
		FILETIME ftKeyCreate2;
		FILETIME ftKeyExpiry2;

		S3_ADMIN_USER_KEY_INFO()
		{
			ZeroFT(ftKeyCreate1);
			ZeroFT(ftKeyExpiry1);
			ZeroFT(ftKeyCreate2);
			ZeroFT(ftKeyExpiry2);
		}
	};

	enum class E_S3_VERSIONING : BYTE
	{
		Off,
		On,
		Suspended
	};

	// stream support
	typedef void(*UPDATE_PROGRESS_CB)(int iProgress, void *pContext);

	struct ECSUTIL_EXT_CLASS STREAM_DATA_ENTRY
	{
		bool bLast;
		CBuffer Data;
		ULONGLONG ullOffset;
		STREAM_DATA_ENTRY()
			: bLast(false)
			, ullOffset(0)
		{}
		STREAM_DATA_ENTRY(bool bLastParam, const CBuffer& DataParam, ULONGLONG ullOffsetParam)
			: bLast(bLastParam)
			, Data(DataParam)
			, ullOffset(ullOffsetParam)
		{}
	};

	struct ECSUTIL_EXT_CLASS STREAM_CONTEXT
	{
		CSharedQueue<STREAM_DATA_ENTRY> StreamData;
		UPDATE_PROGRESS_CB UpdateProgressCB;
		void *pContext;
		int iAccProgress;						// how much data has been read so far
		bool bMultiPart;
		ULONGLONG ullTotalSize;					// on receive, keep track of the total size of the transfer
		STREAM_CONTEXT()
			: UpdateProgressCB(nullptr)
			, pContext(nullptr)
			, iAccProgress(0)
			, bMultiPart(false)
			, ullTotalSize(0ULL)
		{}
	};

	// S3 structs
	struct ECSUTIL_EXT_CLASS S3_DELETE_ENTRY
	{
		CString sKey;
		CString sVersionId;
		S3_DELETE_ENTRY(LPCTSTR pszKey = nullptr, LPCTSTR pszVersionId = nullptr)
			: sKey(pszKey)
			, sVersionId(pszVersionId)
		{}
		int Compare(const S3_DELETE_ENTRY& rec) const
		{
			int iDiff = sKey.Compare(rec.sKey);
			if (iDiff != 0)
				return iDiff;
			return sVersionId.Compare(rec.sVersionId);
		}
		bool operator == (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) == 0;
		};
		bool operator != (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) != 0;
		};
		bool operator < (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) < 0;
		};
		bool operator <= (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) <= 0;
		};
		bool operator > (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) > 0;
		};
		bool operator >= (const S3_DELETE_ENTRY& rec) const
		{
			return Compare(rec) >= 0;
		};
	};

	struct ECSUTIL_EXT_CLASS S3_BUCKET_INFO
	{
		CString sName;
		FILETIME ftCreationDate;
		S3_BUCKET_INFO()
		{
			ZeroFT(ftCreationDate);
		}
		void Empty()
		{
			sName.Empty();
			ZeroFT(ftCreationDate);
		}
	};

	struct ECSUTIL_EXT_CLASS S3_SERVICE_INFO
	{
		CString sOwnerID;
		CString sOwnerDisplayName;
		std::list<S3_BUCKET_INFO> BucketList;
	};

	struct ECSUTIL_EXT_CLASS S3_UPLOAD_PART_ENTRY_EVENT
	{
		CSharedQueueEvent QueueEvent;				// event linked to StreamQueue

		S3_UPLOAD_PART_ENTRY_EVENT()
		{}

		// copy constructor
		S3_UPLOAD_PART_ENTRY_EVENT(const S3_UPLOAD_PART_ENTRY_EVENT& src)
		{
			(void)src;
		};

		const S3_UPLOAD_PART_ENTRY_EVENT& operator =(const S3_UPLOAD_PART_ENTRY_EVENT& src)
		{
			if (&src == this)
				return *this;
			return *this;
		};		//lint !e1539	// members not assigned by assignment operator
	};

	struct ECSUTIL_EXT_CLASS S3_UPLOAD_PART_ENTRY
	{
		UINT uPartNum;						// part number
		CString sETag;						// ETag for part
		CBuffer Checksum;					// if MD5, checksum for the current part
		ULONGLONG ullPartSize;				// size of this part, in bytes. if not the last part, it can't be < 5MB
		ULONGLONG ullBaseOffset;			// base offset of this part in the file
		STREAM_CONTEXT StreamQueue;			// queue used to send data to the HTTP upload thread
		S3_UPLOAD_PART_ENTRY_EVENT Event;	// holds all fields that can't be assigned
		bool bInProcess;					// set if it was pushed onto the thread pool queue
		bool bComplete;						// if set, this entry is done
		DWORD dwRetryNum;					// keep track of how many retries were needed for this part
		ULONGLONG ullCursor;				// current point in transfer

		S3_UPLOAD_PART_ENTRY()
			: uPartNum(0)
			, ullPartSize(0ULL)
			, ullBaseOffset(0ULL)
			, bInProcess(false)
			, bComplete(false)
			, dwRetryNum(0)
			, ullCursor(0ULL)
		{}
	};

	struct ECSUTIL_EXT_CLASS S3_UPLOAD_PART_INFO
	{
		CString sResource;					// HTTP resource used
		CString sBucket;					// bucket name
		CString sKey;						// object key
		CString sUploadId;					// multipart upload ID
	};

	struct ECSUTIL_EXT_CLASS S3_LIST_MULTIPART_UPLOADS_ENTRY
	{
		CString sKey;
		CString sUploadId;
		CString sInitiatorId;
		CString sInitiatorDisplayName;
		CString sOwnerId;
		CString sOwnerDisplayName;
		CString sStorageClass;
		FILETIME ftInitiated;

		S3_LIST_MULTIPART_UPLOADS_ENTRY()
		{
			ZeroFT(ftInitiated);
		}

		void EmptyRec()
		{
			sKey.Empty();
			sUploadId.Empty();
			sInitiatorId.Empty();
			sInitiatorDisplayName.Empty();
			sOwnerId.Empty();
			sOwnerDisplayName.Empty();
			sStorageClass.Empty();
			ZeroFT(ftInitiated);
		}
	};

	struct ECSUTIL_EXT_CLASS S3_LIST_MULTIPART_UPLOADS
	{
		CString sBucket;
		UINT uMaxUploads;
		std::list<S3_LIST_MULTIPART_UPLOADS_ENTRY> ObjectList;

		S3_LIST_MULTIPART_UPLOADS()
			: uMaxUploads(0)
		{}
	};

	enum E_S3_ACL_VALUES : BYTE
	{
		AAV_INVALID,			// not a valid ACL entry
		AAV_NONE,				// no access
		AAV_READ,				// read-only access
		AAV_WRITE,				// write-only access
		AAV_FULL_CONTROL,		// read/write access
		AAV_READ_ACP,			// read permissions
		AAV_WRITE_ACP,			// write permissions
	};

	struct ECSUTIL_EXT_CLASS ACL_ENTRY
	{
		CString sID;			// user or group name
		CString sDisplayName;
		E_S3_ACL_VALUES Acl;	// access for user or group
		bool bGroup;			// if set, group ACL Entry

		ACL_ENTRY()
			: Acl(AAV_INVALID)
			, bGroup(false)
		{}

		ACL_ENTRY(LPCTSTR pszUID, E_S3_ACL_VALUES AclParam, bool bGroupParam)
			: sID(pszUID)
			, Acl(AclParam)
			, bGroup(bGroupParam)
		{}

		bool operator < (const ACL_ENTRY& rec) const
		{
			return sID < rec.sID;
		};

		CString GetAclString() const
		{
			switch (Acl)
			{
			case AAV_NONE: return _T("NONE");
			case AAV_READ: return _T("READ");
			case AAV_WRITE: return _T("WRITE");
			case AAV_FULL_CONTROL: return _T("FULL_CONTROL");
			case AAV_READ_ACP: return _T("READ_ACP");
			case AAV_WRITE_ACP: return _T("WRITE_ACP");
			default:
				break;
			}
			return _T("INVALID");
		}

		void Clear(void)
		{
			Acl = AAV_INVALID;
			bGroup = false;
			sID.Empty();
			sDisplayName.Empty();
		}
	};

	static CString GetAclHeaderString(E_S3_ACL_VALUES Acl)
	{
		switch (Acl)
		{
		case AAV_NONE: return _T("");
		case AAV_READ: return _T("x-amz-grant-read");
		case AAV_WRITE: return _T("x-amz-grant-write");
		case AAV_FULL_CONTROL: return _T("x-amz-grant-full-control");
		case AAV_READ_ACP: return _T("x-amz-grant-read-acp");
		case AAV_WRITE_ACP: return _T("x-amz-grant-write-acp");
		default:
			break;
		}
		return _T("");
	}

	typedef std::list<ACL_ENTRY> UIDList_t;

	struct ECSUTIL_EXT_CLASS ECS_CERT_INFO
	{
		CString sCertName;								// if certificate error, these fields contain info from the server cert
		CString sCertSubject;							// Certificate Subject
		CString sCertSubjectAltName;					// Subject Alternative Names (SAN) extension if available
		CBuffer SerializedCert;							// if self-signed cert, this contains the certificate from the server
	};

	struct ECSUTIL_EXT_CLASS S3_ERROR_BASE
	{
		DWORD dwError;					// WIN32 error
		DWORD dwHttpError;				// HTTP error
		DWORD dwSecureError;			// if HTTPS error, additional info
		E_S3_ERROR_TYPE S3Error;		// S3 error
		CString sS3Code;				// S3: error code
		CString sS3Resource;			// S3: resource associated with the error
		CString sS3RequestID;			// S3: request ID associated with the error
		CString sDetails;				// ECS Admin: additional details
		CString sHostAddr;				// IP/FQDN:port of connection that failed
		ECS_CERT_INFO CertInfo;			// if secure error, a copy of important fields in the certificate

		S3_ERROR_BASE(DWORD dwErrorParam = ERROR_SUCCESS)
			: dwError(dwErrorParam)
			, dwHttpError(0)
			, dwSecureError(0)
			, S3Error(S3_ERROR_SUCCESS)
		{}

		bool IfError() const
		{
			return (dwError != ERROR_SUCCESS)
				|| (dwHttpError >= 400)
				|| (S3Error != S3_ERROR_SUCCESS);
		}
		CString Format(bool bOneLine = false) const;
		bool operator ==(const S3_ERROR_BASE &Error) const
		{
			return (dwError == Error.dwError)
				&& (dwHttpError == Error.dwHttpError)
				&& (S3Error == Error.S3Error)
				&& (sS3Code == Error.sS3Code);
		}
		bool operator !=(const S3_ERROR_BASE &Error) const
		{
			return !operator ==(Error);
		}
		bool IfNotFound(void) const
		{
			return ((dwError == (DWORD)HTTP_E_STATUS_NOT_FOUND)
				|| (S3Error == S3_ERROR_NoSuchKey)
				|| (dwHttpError == HTTP_STATUS_NOT_FOUND));
		}
	};

	struct ECSUTIL_EXT_CLASS S3_ERROR : public S3_ERROR_BASE
	{
		S3_ERROR(DWORD dwErrorParam = ERROR_SUCCESS)
			: S3_ERROR_BASE(dwErrorParam)
		{}

		S3_ERROR(const S3_ERROR& src)
			: S3_ERROR_BASE(src)
		{
			SetError();						// if http error, set dwError code to reflect it
		}
		const S3_ERROR& operator =(const S3_ERROR& src)
		{
			if (&src == this)
				return *this;
			(void)S3_ERROR_BASE::operator =(src);
			SetError();
			return *this;
		};
	private:
		void SetError(void);
	};

	class CS3ErrorInfo : public CErrorInfo
	{
	public:
		CECSConnection::S3_ERROR Error;

		CS3ErrorInfo()
		{
		}

		CS3ErrorInfo(const CECSConnection::S3_ERROR& ErrorParam)
		{
			Error = ErrorParam;
		}

		CS3ErrorInfo(LPCTSTR pszFile, DWORD dwLineParam, const CECSConnection::S3_ERROR& ErrorParam)
		{
			sFile = pszFile;
			dwLine = dwLineParam;
			Error = ErrorParam;
		}

		CS3ErrorInfo(LPCTSTR pszFile, DWORD dwLineParam, NTSTATUS Status, const CECSConnection::S3_ERROR& ErrorParam, LPCTSTR pszAdditionalInfo = nullptr)
		{
			sFile = pszFile;
			dwLine = dwLineParam;
			dwError = Status;
			Error = ErrorParam;
			if (pszAdditionalInfo != nullptr)
				sAdditionalInfo = pszAdditionalInfo;
		}

		CS3ErrorInfo(const CErrorInfo& ErrorInfo)
			: CErrorInfo(ErrorInfo)
		{
		}

		bool IfError() const
		{
			return Error.IfError() || (dwError != ERROR_SUCCESS);
		}
		CString Format() const
		{
			S3_ERROR TmpAtError = Error;
			if ((TmpAtError.dwError == ERROR_SUCCESS) && (dwError != ERROR_SUCCESS))
				TmpAtError.dwError = dwError;
			CString sMsg(TmpAtError.Format());
			if (!sAdditionalInfo.IsEmpty())
				sMsg += _T("\r\n") + sAdditionalInfo;
			return sMsg;
		}
	};

	struct ECSUTIL_EXT_CLASS S3_SYSTEM_METADATA
	{
		FILETIME ftLastMod;				// Last user-data modification time
		ULONGLONG llSize = 0ULL;		// Object size in bytes (size)
		DWORD dwRetentionSeconds = 0;	// value of x-emc-retention-period. For HEAD on a bucket, this is the bucket-level retention period
		bool bIsLatest = false;			// only used for S3 versions: indicates it is the latest version
		bool bDeleted = false;			// object has been deleted
		CString sVersionId;				// only used for S3 versions: version ID of object
		CString sETag;					// S3: unique key used to determine if the file has changed
		CString sOwnerDisplayName;		// S3: owner display name
		CString sOwnerID;				// S3: owner ID

		S3_SYSTEM_METADATA()
		{
			ZeroFT(ftLastMod);
		}

		void Empty()
		{
			ZeroFT(ftLastMod);
			llSize = 0ULL;
			dwRetentionSeconds = 0;
			sETag.Empty();
			sOwnerDisplayName.Empty();
			bIsLatest = false;
			bDeleted = false;
			sVersionId.Empty();
		}

		bool operator==(const S3_SYSTEM_METADATA& rec) const
		{
			return (ftLastMod == rec.ftLastMod)
				&& (llSize == rec.llSize)
				&& (dwRetentionSeconds == rec.dwRetentionSeconds)
				&& (sETag == rec.sETag)
				&& (sOwnerDisplayName == rec.sOwnerDisplayName)
				&& (sOwnerID == rec.sOwnerID)
				&& (bIsLatest == rec.bIsLatest)
				&& (bDeleted == rec.bDeleted)
				&& (sVersionId == rec.sVersionId);
		}

		bool operator!=(const S3_SYSTEM_METADATA& rec) const
		{
			return !operator==(rec);
		}
	};

	struct ECSUTIL_EXT_CLASS DIR_ENTRY
	{
		CString sName;
		bool bDir;				// if set, subdir
		S3_SYSTEM_METADATA Properties;

		DIR_ENTRY()
			: bDir(false)
		{
		}

		bool operator < (const DIR_ENTRY& rec) const
		{
			int iComp = sName.Compare(rec.sName);
			return iComp < 0;
		};
	};
	typedef std::list<DIR_ENTRY> DirEntryList_t;

	// function to check if the current request needs to be aborted (thread exit or application termination)
	// returns true if current request needs to be canceled immediately
	typedef bool (*TEST_SHUTDOWN_CB)(void *pContext);
	typedef void (*ECS_DISCONNECT_CB)(CECSConnection *pHost, const CS3ErrorInfo *pError, bool *pbDisconnected);
	typedef CString (*GET_HTTP_ERROR_TEXT_CB)(DWORD dwHttpError);
	typedef void (*DIR_LISTING_CB)(size_t Size, void *pContext);

public:
	struct XML_DIR_LISTING_CONTEXT;

	struct XML_DIR_LISTING_CONTEXT
	{
		// parameters from listing
		CString sPathIn;
		CString sObjName;				// optional object name to add to prefix

		bool bGotRootElement;			// sanity check. we need to see the root element to verify that the XML looks good
		bool bSingle;					// just get some entries. not all
		bool bS3Versions;				// S3 version listing
		bool bGotKey;					// set if it saw any key. this is used to determine if the folder exists at all
		DirEntryList_t *pDirList;
		CCriticalSection csDirList;
		CECSConnection::DIR_ENTRY Rec;
		LPCTSTR pszSearchName;
		CString *psRetSearchName;

		S3_ERROR Error;

		// S3 fields
		bool bIsTruncated;
		CString sPrefix;					// the prefix received from the command results
		CString sPrefixNoObj;				// if pszObjName was specified, this is the prefix minus the object name
		CString sS3NextMarker;				// passed to marker in next request
		CString sS3NextKeyMarker;			// passed to key-marker in next request
		CString sS3NextVersionIdMarker;		// passed to version-id-marker in next request
		CString sLastFullObjName;			// may be used as a next marker if none specified

		XML_DIR_LISTING_CONTEXT()
			: bGotRootElement(false)
			, bSingle(false)
			, bS3Versions(false)
			, bGotKey(false)
			, pDirList(nullptr)
			, pszSearchName(nullptr)
			, psRetSearchName(nullptr)
			, bIsTruncated(false)
		{
		}

		void EmptyRec()
		{
			Rec.sName.Empty();
			Rec.Properties.Empty();
		}
	};

	struct HEADER_REQ
	{
		CString sHeader;
		std::list<CString> ContentList;

		HEADER_REQ(LPCTSTR pszHeader = nullptr)
		{
			if (pszHeader != nullptr)
				sHeader = pszHeader;
		}
	};

	struct HEADER_STRUCT
	{
		CString sHeader;
		CString sContents;

		HEADER_STRUCT(LPCTSTR pszHeader = nullptr, LPCTSTR pszContents = nullptr)
		{
			if (pszHeader != nullptr)
				sHeader = pszHeader;
			if (pszContents != nullptr)
				sContents = pszContents;
		}
	};

	struct GLOBAL_PERF_POINTERS
	{
		volatile ULONGLONG *pullBytesSent;
		volatile ULONGLONG *pullBytesRcv;
		GLOBAL_PERF_POINTERS(volatile ULONGLONG *pullBytesSentParam = nullptr, volatile ULONGLONG *pullBytesRcvParam = nullptr)
			: pullBytesSent(pullBytesSentParam)
			, pullBytesRcv(pullBytesRcvParam)
		{}
	};

private:
	struct HTTP_CALLBACK_EVENT
	{
		CEvent evCmd;								// event is fired when async callback is received
		CEvent evExit;								// event is fired when callback has cleared all destructors

		HTTP_CALLBACK_EVENT()
			: evCmd(false, true)
			, evExit(false, true)
		{
		}

		// copy constructor
		HTTP_CALLBACK_EVENT(const HTTP_CALLBACK_EVENT& src)
		{
			(void)src;
		};

		const HTTP_CALLBACK_EVENT& operator =(const HTTP_CALLBACK_EVENT& src)
		{
			if (&src == this)
				return *this;
			return *this;
		};		//lint !e1539	// members not assigned by assignment operator
	};

	struct CMD_RECEIVED
	{
		DWORD dwInternetStatus = 0;
		FILETIME ftCmdTime;
		CMD_RECEIVED()
		{
			ZeroFT(ftCmdTime);
		}
	};

	// http async context
	struct HTTP_CALLBACK_CONTEXT
	{
		CCriticalSection csContext;
		HTTP_CALLBACK_EVENT Event;					// event is fired when async callback is received
		WINHTTP_ASYNC_RESULT Result;				// if error, this contains the error code
		std::list<CMD_RECEIVED> CallbacksReceived;		// the last callbacks received
		DWORD dwReadLength = 0;						// WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE, WINHTTP_CALLBACK_STATUS_READ_COMPLETE
		DWORD dwBytesWritten = 0;					// WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE
		DWORD dwSecureError = 0;					// explanation for SSL errors (WINHTTP_CALLBACK_STATUS_FLAG_...)
		long lExitFlag = 0;							// set nonzero when callback has run all destructors and the underlying structure can be deleted - use Interlock routines for access
		bool bHeadersAvail = false;					// WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE
		bool bSendRequestComplete = false;			// WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE
		bool bFailed = false;						// WINHTTP_CALLBACK_STATUS_REQUEST_ERROR
		bool bComplete = false;						// set if the command has completed
		bool bHandleCreated = false;				// WINHTTP_CALLBACK_STATUS_HANDLE_CREATED
		bool bHandleClosing = false;				// WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING
		bool *pbCallbackRegistered = nullptr;		// pointer to flag indicating the callback has been registered
		bool bDisableSecureLog = false;				// if set, don't log security errors in the callback
		BYTE *pReadData = nullptr;					// WINHTTP_CALLBACK_STATUS_READ_COMPLETE
		CECSConnection *pHost = nullptr;			// allow access to the host record

		HTTP_CALLBACK_CONTEXT()
		{
			ZeroMemory(&Result, sizeof(Result));
			Reset();
		}

		void Reset()
		{
			CSingleLock lock(&csContext, true);
			ZeroMemory(&Result, sizeof(Result));
			dwReadLength = 0;
			dwBytesWritten = 0;
			bHeadersAvail = false;
			bSendRequestComplete = false;
			bFailed = false;
			bComplete = false;
			pReadData = nullptr;
			bHandleCreated = false;
			bHandleClosing = false;
			pbCallbackRegistered = nullptr;
			CallbacksReceived.clear();
			bDisableSecureLog = false;
			dwSecureError = 0;
			pHost = nullptr;
			Event.evCmd.ResetEvent();
		}
	};

	struct ABORT_ENTRY
	{
		const bool *pbAbort;			// pointer to abort bool
		bool bAbortIfTrue;				// determines sense of pbAbort
		TEST_SHUTDOWN_CB ShutdownCB;
		void *pShutdownContext;			// context to pass back to shutdown callback

		ABORT_ENTRY()
			: pbAbort(nullptr)
			, bAbortIfTrue(true)
			, ShutdownCB(nullptr)
			, pShutdownContext(nullptr)
		{
		}
	};

	struct SESSION_MAP_KEY
	{
		CString sHostEntry;					// host entry
		CString sIP;						// IP/hostname
		long lKey;							// random number to make the key unique
		SESSION_MAP_KEY()
			: lKey(0)
		{}
		int CompareEntry(const SESSION_MAP_KEY& Src) const
		{
			int iDiff = sHostEntry.Compare(Src.sHostEntry);
			if (iDiff == 0)
				iDiff = sIP.Compare(Src.sIP);
			if (iDiff == 0)
				iDiff = COMPARE(lKey, Src.lKey);
			return iDiff;
		}
		bool operator <(const SESSION_MAP_KEY& Src) const
		{
			return CompareEntry(Src) < 0;
		}
		CString Format(void) const
		{
			return _T("Session: ") + sHostEntry + _T(", ") + sIP + _T(", ") + FmtNum(lKey);
		}
	};

	struct SESSION_MAP_VALUE
	{
		bool bInUse;								// if true, entry is in use
		bool bKillWhenDone;							// the host entry has changed. when releasing this entry, close and delete it so it gets recreated with the new info
		CInternetHandle hSession;
		CInternetHandle hConnect;
		FILETIME ftIdleTime;						// set when entry is freed
		SESSION_MAP_VALUE()
			: bInUse(false)
			, bKillWhenDone(false)
			, hSession(nullptr)
			, hConnect(nullptr)
		{
			GetSystemTimeAsFileTime(&ftIdleTime);
		}
		void CloseAll(void)
		{
			if (hConnect.IfOpen())
				(void)hConnect.CloseHandle();
			if (hSession.IfOpen())
				(void)hSession.CloseHandle();
		}
		~SESSION_MAP_VALUE()
		{
			CloseAll();
		}
		CString Format(void) const
		{
			return CString(bInUse ? _T("InUse, ") : _T("free, "))
				+ (bKillWhenDone ? _T("Kill, ") : _T("NoKill, "))
				+ _T("hSession:") + FmtNum((HINTERNET)hSession, 0, false, true) + _T(", ")
				+ _T("hConnect:") + FmtNum((HINTERNET)hConnect, 0, false, true);
		}
	};

	class CECSConnectionSession
	{
	private:
		SESSION_MAP_KEY Key;
	public:
		SESSION_MAP_VALUE *pValue;
		CECSConnectionSession();
		~CECSConnectionSession();
		void AllocSession(LPCTSTR pszHost, LPCTSTR pszIP);
		void ReleaseSession(void) throw();
		CString Format(void) const;
	};
	static CCriticalSection csSessionMap;
	static std::map<SESSION_MAP_KEY, SESSION_MAP_VALUE> SessionMap;			// protected by csSessionMap
	static long lSessionKeyValue;											// used to make session key unique

	// all state fields. These are not copied during assignment or copy constructor
	struct CECSConnectionState
	{
		volatile LONG ulReferenceCount;			// if 0, no threads are using this record
		FILETIME ftLastUsed;					// time of last use. used in garbage collect
		CECSConnection *pECSConnection;			// pointer to parent record
		CECSConnectionSession Session;			// current allocated session (cached hSession and hConnect)
		CInternetHandle hRequest;				// request handle
		bool bCallbackRegistered;
		bool bS3Admin;							// admin API
		bool bSaveCertInfo;						// save the certificate info whether there is an error or not
		std::map<CString,HEADER_STRUCT> Headers;
		UINT iIPList;							// index into IPList showing currently used
		std::deque<CString> IPListLocal;				// local copy of IPListHost to be used only for this request
		CEvent evThrottle;						// triggered if throttling and throttle interval was refreshed
		HTTP_CALLBACK_CONTEXT CallbackContext;
		DWORD dwCurrentThread;
		DWORD dwProxyAuthScheme;				// if non-zero, proxy requires authorization (WINHTTP_AUTH_SCHEME_...)
		DWORD dwAuthScheme;						
		DWORD dwSecureError;					// explanation for SSL errors (WINHTTP_CALLBACK_STATUS_FLAG_...)
		bool bDisableSecureLog;					// if set, don't log security errors in the callback
		ECS_CERT_INFO CertInfo;				// holds certificate info if it is from an unknown CA
		std::list<S3_DELETE_ENTRY> S3DeletePathList;	// accumulated list of objects to delete. used during DeleteS3
		ULONGLONG ullReadBytes;					// keep track of number of received bytes in a stream receive
		DWORD dwSecurityFlagsAdd;				// flags to add to security options from default
		DWORD dwSecurityFlagsSub;				// flags to subtract from security options from default
		CString sHTTPUser;						// for HTTP authentication
		CStringPassword sHTTPPassword;					// for HTTP authentication
		CString sX_SDS_AUTH_TOKEN;				// for HTTP authentication: after login this contains the auth token used on subsequent calls
		std::list<ABORT_ENTRY> AbortList;			// list of abort entries
		mutable CRWLock rwlAbortList;			// lock used for AbortList

		// v4 auth chunk info
		UINT uS3AuthV4ChunkMetadataSize;
		UINT uS3AuthV4ChunkMetadataOffset;
		CStringA sChunkMetadataFormatA;

		CECSConnectionState()
			: ulReferenceCount(0)
			, pECSConnection(nullptr)
			, hRequest(nullptr)
			, bCallbackRegistered(false)
			, bS3Admin(false)
			, bSaveCertInfo(false)
			, iIPList(0)
			, dwCurrentThread(0)
			, dwProxyAuthScheme(0)
			, dwAuthScheme(0)
			, dwSecureError(0)
			, bDisableSecureLog(false)
			, ullReadBytes(0ULL)
			, dwSecurityFlagsAdd(0)
			, dwSecurityFlagsSub(0)
			, uS3AuthV4ChunkMetadataSize(0)
			, uS3AuthV4ChunkMetadataOffset(0)
		{
			ZeroFT(ftLastUsed);
		}
		~CECSConnectionState()
		{
			// Close any open handles.
			CloseRequest();
			if (pECSConnection != nullptr)
				pECSConnection->SetPerfStateSize(-1);
			pECSConnection = nullptr;
		}

		// copy constructor
		CECSConnectionState(const CECSConnectionState& src)
			: ulReferenceCount(0)
			, pECSConnection(nullptr)
			, hRequest(nullptr)
			, bCallbackRegistered(false)
			, bS3Admin(false)
			, bSaveCertInfo(false)
			, iIPList(0)
			, dwCurrentThread(0)
			, dwProxyAuthScheme(0)
			, dwAuthScheme(0)
			, dwSecureError(0)
			, bDisableSecureLog(false)
			, ullReadBytes(0ULL)
			, dwSecurityFlagsAdd(0)
			, dwSecurityFlagsSub(0)
			, uS3AuthV4ChunkMetadataSize(src.uS3AuthV4ChunkMetadataSize)
			, uS3AuthV4ChunkMetadataOffset(src.uS3AuthV4ChunkMetadataOffset)
		{
			(void)src;
			ZeroFT(ftLastUsed);
		};

		const CECSConnectionState& operator =(const CECSConnectionState& src)
		{
			if (&src == this)
				return *this;
			return *this;
		};		//lint !e1539	// members not assigned by assignment operator
		void CloseRequest(bool bSaveCert = false) throw();
	};

	struct CECSConnectionStateCS
	{
		mutable CSimpleRWLock rwlStateMap;		// lock for StateMap
		mutable std::map<DWORD, std::shared_ptr<CECSConnectionState>> StateMap;

		CECSConnectionStateCS()
		{
		}

		// copy constructor
		CECSConnectionStateCS(const CECSConnectionStateCS& src)
		{
			(void)src;
		};

		const CECSConnectionStateCS& operator =(const CECSConnectionStateCS& src)
		{
			return *this;
		};		//lint !e1539	// members not assigned by assignment operator
	};

	CString sSecret;
	CString sUser;
	CString sHost;
	CString sUserAgent;
	std::deque<CString> IPListHost;				// list of IP addresses/DNS host names to access this server. protected by rwlIPListHost
	mutable CSimpleRWLock rwlIPListHost;	// lock for IPListHost
	INTERNET_PORT Port = INTERNET_DEFAULT_HTTP_PORT;
	bool bSSL = false;								// use HTTPS if set
	bool bUseDefaultProxy = true;					// if set and sProxy is empty, use default proxy (see netsh winhttp)
	bool bTestConnection = false;					// if test connection, timeout quickly and don't do anything unnecessary for the test
	CString sProxy;							// optional proxy server
	DWORD dwProxyPort = 0;						// if sProxy not emtpy, contains the port for the proxy
	CString sProxyUser;						// proxy server authentication
	CStringPassword sProxyPassword;					// proxy server password
	DWORD dwHttpsProtocol = 0;					// bit field of acceptable protocols
	bool bCheckShutdown = true;					// if set, then abort request if during service shutdown (default)
	ECS_DISCONNECT_CB DisconnectCB = nullptr;			// disconnect callback
	DWORD dwMaxStreamQueueSizeRecv = DefaultMaxStreamQueueSizeRecv;	// maximum receive queue size

	// S3 settings
	CString sS3KeyID;						// S3 Key ID
	CString sS3Region = _T("us-east-1");						// S3 region (ie us-east-1)
	bool bS3AuthV4 = true;							// true if S3 V4 authorization
	UINT uS3AuthV4ChunkSize = DefaultS3AuthV4ChunkSize;				// if S3 V4 auth, the size of the chunks

	mutable CSimpleRWLock lwrS3V4SigningKey;// critical section protecting GlobalS3V4SigningKey
	CBuffer GlobalS3V4SigningKey;			// if S3 V4, calculated signing key (good for a week)
	FILETIME ftS3V4SigningKey;				// timestamp when signing key was created

	CECSConnectionStateCS StateList;		// this is in a substruct because we don't want the state list to be assigned or copied

	// timeout values
	DWORD dwWinHttpOptionConnectRetries = 0;
	DWORD dwWinHttpOptionConnectTimeout = 0;	// default 60 sec
	DWORD dwWinHttpOptionReceiveResponseTimeout = 0;	// default 90 sec
	DWORD dwWinHttpOptionReceiveTimeout = 0;	// default 30 sec
	DWORD dwWinHttpOptionSendTimeout = 0;		// default 30 sec
	DWORD dwLongestTimeout = 0;					// use this to determine the longest time to wait for any one command to finish
	DWORD dwBadIPAddrAge = 0;					// how long a bad IP entry in the host entry will stay bad before being put back into service (seconds)

	DWORD dwMaxWriteRequest = MaxWriteRequest;				// if non-zero, this specifies the maximum write request. larger requests should be broken into smaller ones

	DWORD dwHttpSecurityFlags = 0;				// global default for security flags (see WinHttpSetOption, WINHTTP_OPTION_SECURITY_FLAGS)

	WINHTTP_SECURITY_INFO* pSecurityInfo = nullptr;			// if non-nullptr, at the next successful SendRequest, set SecurityInfo
	DWORD* pSecurityInfoError = nullptr;					// error returned when trying to get security info

	// throttle info

	// CThrottleTimerThread
	// controls the throttle thread
	struct CThrottleTimerThread : public CSimpleWorkerThread
	{
		FILETIME ftLast;					// last activation - used to determine the exact time between calls
		CThrottleTimerThread();
		~CThrottleTimerThread();
	protected:
		void DoWork();
	public:
		bool InitInstance();
	};

	struct THROTTLE_INFO
	{
		int iBytesSec;						// bytes/sec throttle rate for this URL
		int iBytesCurInterval;				// how many bytes can be sent in the current interval

		THROTTLE_INFO()
		{
			iBytesSec = 0;
			iBytesCurInterval = 0;
		}
	};
	struct THROTTLE_REC
	{
		THROTTLE_INFO Upload;
		THROTTLE_INFO Download;
	};
	static bool bInitialized;							// starts out false. If false, timeouts are very short. must call SetInitialized to get regular timeouts
	static CThrottleTimerThread TimerThread;			// throttle timer thread
	static std::map<CString,THROTTLE_REC> ThrottleMap;		// global map used by all CECSConnection objects, key is host name
	static CCriticalSection csThrottleMap;				// critical section protecting ThrottleMap
	static std::list<CECSConnection *> ECSConnectionList;	// list of all CECSConnection objects (protected by csThrottleMap)
	static std::list<XML_DIR_LISTING_CONTEXT *> DirListList;	// listing of current dir listing operations
	static CCriticalSection csDirListList;				// critical section protecting DirListList
	static DWORD dwGlobalHttpsProtocol;					// bit field of acceptable protocols
	static DWORD dwS3BucketListingMax;					// maxiumum number of items to return on a bucket listing (S3). Default = 1000 (cannot be larger than 1000)

	static DWORD dwMaxRetryCount;						// max retries for HTTP command
	static DWORD dwPauseBetweenRetries;					// pause between retries (millisec)
	static DWORD dwPauseAfter500Error;					// pause between retries after HTTP 500 error (millisec)

public:
	static std::set<CString> SystemMDSet;					// set of system metadata fields that can be indexed
	static CString sAmzMetaPrefix;						// just a place to hold "x-amz-meta-"

private:

	// BadIPMap
	// holds any IP address that seems to be bad
	// if an IP fails, it will be put into this map for a bit
	// when it is in the map, it will not be used in any connection attempts
	// when it times out it will be put into rotation. if it fails again - back on the map
	struct BAD_IP_KEY
	{
		CString sHostName;				// host entry name
		CString sIP;					// IP address or FQDN

		BAD_IP_KEY()
		{
		}
		BAD_IP_KEY(const CString& sHostParam, const CString& sIPParam)
		{
			sHostName = sHostParam;
			sIP = sIPParam;
		}
		int Compare(const BAD_IP_KEY& Key) const
		{
			int iDiff = sHostName.Compare(Key.sHostName);
			if (iDiff != 0)
				return iDiff;
			return sIP.Compare(Key.sIP);
		}
		bool operator < (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) < 0;
		}
		bool operator > (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) > 0;
		}
		bool operator <= (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) <= 0;
		}
		bool operator >= (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) >= 0;
		}
		bool operator == (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) == 0;
		}
		bool operator != (const BAD_IP_KEY& Key) const
		{
			return Compare(Key) != 0;
		}
	};
	struct BAD_IP_ENTRY
	{
		FILETIME ftError;				// time that error occurred
		CS3ErrorInfo ErrorInfo;		// last error received
		BAD_IP_ENTRY()
		{
			ZeroFT(ftError);
		}
		BAD_IP_ENTRY(const CS3ErrorInfo& ErrorInfoParam)
		{
			ErrorInfo = ErrorInfoParam;
			GetSystemTimeAsFileTime(&ftError);
		}
	};

	enum class E_S3_V4_PAYLOAD : BYTE
	{
		Signed,
		Chunked,
		Unsigned
	};

	struct CStateRef
	{
		CECSConnection *pConn;
		std::shared_ptr<CECSConnectionState> Ref;
		CStateRef(CECSConnection *pConnParam = nullptr);
		~CStateRef();
	};

	static CCriticalSection csBadIPMap;
	static std::map<BAD_IP_KEY,BAD_IP_ENTRY> BadIPMap;
	static std::map<CString,UINT> LoadBalMap;					// global IP selector for all entries

	// global performance counters
	static CSimpleRWLock rwlGlobalPerf;
	static std::list<GLOBAL_PERF_POINTERS> GlobalPerfList;
	// per-instance performance counters
	volatile ULONGLONG *pullPerfBytesSent = nullptr;
	volatile ULONGLONG *pullPerfBytesRcv = nullptr;
	volatile ULONG *pulStateMapSize = nullptr;
	volatile ULONG *pulMaxStateMapSize = nullptr;
	void SetPerfStateSize(long lDiff);

	std::shared_ptr<CECSConnectionState> GetStateBuf();
	BOOL WinHttpQueryHeadersBuffer(__in HINTERNET hRequest, __in DWORD dwInfoLevel, __in_opt LPCTSTR pwszName, __inout CBuffer& RetBuf, __inout LPDWORD lpdwIndex);
	static CString GetCanonicalTime(const SYSTEMTIME *pstTime = nullptr);
	static FILETIME ParseCanonicalTime(LPCTSTR pszCanonTime);
	void sign(const CString& secretStr, const CString& hashStr, CString& encodedStr);
	CString signRequestS3v2(const CString& secretStr, const CString& method, const CString& resource, const std::map<CString, HEADER_STRUCT>& headers, LPCTSTR pszExpires = nullptr);
	CString signRequestS3v4(const CString& secretStr, const CString& method, const CString& resource, const std::map<CString, HEADER_STRUCT>& headers, const void *pData,
		DWORD dwDataLen, E_S3_V4_PAYLOAD PayloadType, ULONGLONG ullTotalLen, ULONGLONG ullTotalPayloadLen, CBuffer& S3SigningKey, CString& sPreviousSignature,
		const SYSTEMTIME& stRequestTime);
	void CreateS3SigningKey(const CString& secretStr, const SYSTEMTIME& stRequestTime, CBuffer& SigningKey);
	CStringA BuildV4ChunkMetadata(UINT uChunkLength, const CString& sSignature);
	void CreateS3V4ChunkMetadata(
		CString& sPreviousSignature,
		CBuffer& S3AuthV4SendBuf,
		UINT& uS3AuthV4SendBufIndex,
		const CString& sEmptySignature,
		const CBuffer& S3SigningKey,
		const SYSTEMTIME& stRequestTime);

	static void CALLBACK HttpStatusCallback(__in  HINTERNET hInternet,__in  DWORD_PTR dwContext,__in  DWORD dwInternetStatus,__in  LPVOID lpvStatusInformation,__in  DWORD dwStatusInformationLength);
	DWORD InitSession();
	void CloseAll();
	void InitHeader(void);
	void AddHeader(LPCTSTR pszHeaderLabel, LPCTSTR pszHeaderText, bool bOverride = true);
	void SetTimeouts(const CInternetHandle& hRequest);
	S3_ERROR SendRequestInternal(LPCTSTR pszMethod, LPCTSTR pszResource, const void *pData, DWORD dwDataLen, CBuffer& RetData, std::list<HEADER_REQ> *pHeaderReq, DWORD dwReceivedDataHint, DWORD dwBufOffset, bool *pbGotServerResponse, STREAM_CONTEXT *pStreamSend, STREAM_CONTEXT *pStreamReceive, ULONGLONG ullTotalLen);
	LPCTSTR GetCurrentServerIP(void);
	void TestAllIPBad(void);
	bool GetNextECSIP(std::map<CString, BAD_IP_ENTRY>& IPUsed);
	void LogBadIPAddr(const std::map<CString,BAD_IP_ENTRY>& IPUsed);
	bool IfMarkIPBad(DWORD dwError);
	void PrepareCmd(void);
	void CleanupCmd(void);
	bool WaitComplete(DWORD dwCallbackExpected);
	bool WaitStreamSend(STREAM_CONTEXT *pStreamSend, const CSharedQueueEvent& MsgEvent);
	DWORD ChooseAuthScheme(DWORD dwSupportedSchemes);
	CString FormatAuthScheme(void);
	// internal version of DirListing allowing it to search for a single file/dir and not return the whole list
	S3_ERROR DirListingInternal(LPCTSTR pszPathIn, DirEntryList_t& DirList, LPCTSTR pszSearchName, CString& sRetSearchName, bool bS3Versions, bool bSingle, LPCTSTR pszObjName, LISTING_NEXT_MARKER_CONTEXT *pNextRequestMarker, TCHAR cDelimiter);
	CString signS3ShareableURL(CString& sResource, const CString& sExpire, const CString& sHostPort);
	void KillHostSessions(void);
	void DeleteS3Send(void);
	void DeleteS3Internal(const std::list<S3_DELETE_ENTRY>& PathList);
	S3_ERROR CopyS3(LPCTSTR pszSrcPath, LPCTSTR pszTargetPath, LPCTSTR pszVersionId, bool bCopyMD, ULONGLONG ullObjSize, const std::list<HEADER_STRUCT> *pMDList);
	void WaitForCallbackDone(CECSConnectionState& State);
	void RecordSecurityInfo(const CStateRef& State);

public:
	CECSConnection();
	~CECSConnection();
	CECSConnection(const CECSConnection& Rec);
	static void Init(void);
	static void SetGlobalHttpsProtocol(DWORD dwGlobalHttpsProtocolParam);
	static void SetS3BucketListingMax(DWORD dwS3BucketListingMaxParam);
	static void SetRetries(DWORD dwMaxRetryCountParam, DWORD dwPauseBetweenRetriesParam = 500, DWORD dwPauseAfter500ErrorParam = 500);
	static DWORD SetRootCertificate(const ECS_CERT_INFO& CertInfo, DWORD dwCertOpenFlags = CERT_STORE_OPEN_EXISTING_FLAG | CERT_SYSTEM_STORE_LOCAL_MACHINE, LPCTSTR pszStoreName = _T("Root"));
	static CString GetSecureErrorText(DWORD dwSecureError);
	static CString FormatSecurityInfo(const WINHTTP_SECURITY_INFO& SecurityInfo);

	static void SetInitialized(void);				// global initialized flag. must be called to set regular timeouts
	void SetSecret(LPCTSTR pszSecret);		// set shared secret string in base64
	void SetUser(LPCTSTR pszUser);			// set user ID
	void SetHost(LPCTSTR pszHost);			// set Host
	void SetIPList(const std::deque<CString>& IPListParam);
	void GetIPList(std::deque<CString>& IPListParam);
	void SetSSL(bool bSSLParam);
	void SetRegion(LPCTSTR pszS3Region);
	void SetS3KeyID(LPCTSTR pszS3KeyID);
	void SetSecurityInfo(WINHTTP_SECURITY_INFO* pSecurityInfoParam = nullptr, DWORD* pSecurityInfoErrorParam = nullptr);		// set a buffer that is filled with the security info at the next successful SendRequest
	CString GetS3KeyID(void);
	static DWORD ParseISO8601Date(LPCTSTR pszDate, FILETIME& ftTime, bool bLocal = false);
	static CString FormatISO8601Date(const FILETIME& ftDate, bool bLocal, bool bMilliSec = true, bool bBasicFormat = false);
	static CString FormatISO8601Date(const SYSTEMTIME& stDateUTC, bool bLocal, bool bMilliSec = true, bool bBasicFormat = false);

	static void SetGlobalPerformanceCounters(const std::list<GLOBAL_PERF_POINTERS>& PerfListParam);
	void SetPerformanceCounters(ULONGLONG *pullPerfBytesSentParam, ULONGLONG *pullPerfBytesRcvParam, ULONG *pulStateMapSizeParam, ULONG *pulMaxStateMapSizeParam);
	void SetHostAuth(bool bAuthV4 = true, UINT uS3AuthV4ChunkSize = DefaultS3AuthV4ChunkSize);
	bool IfS3v4(UINT *puChunkSize = nullptr) const;

	void SetUserAgent(LPCTSTR pszUserAgent);					// typically app name/version. put in 'user agent' field in HTTP protocol
	void SetPort(INTERNET_PORT PortParam);
	void SetProxy(bool bUseDefaultProxyParam, LPCTSTR pszProxy, DWORD dwPort, LPCTSTR pszProxyUser, LPCTSTR pszProxyPassword);
	void SetTest(bool bTestParam);
	void SetHttpsProtocol(DWORD dwHttpsProtocolParam);
	static void SetThrottle(LPCTSTR pszHost, int iUploadThrottleRate, int iDownloadThrottleRate);
	static void TerminateThrottle(void);
	void IfThrottle(bool *pDownloadThrottle, bool *pUploadThrottle);
	void RegisterShutdownCB(TEST_SHUTDOWN_CB ShutdownParamCB, void *pContext);
	void UnregisterShutdownCB(TEST_SHUTDOWN_CB ShutdownParamCB, void *pContext);
	void RegisterAbortPtr(const bool *pbAbort, bool bAbortTrue = true);
	void UnregisterAbortPtr(const bool *pbAbort);
	void CheckShutdown(bool bCheckShutdownParam=true);		// set this to false if you need to do ops during a shutdown
	void RegisterDisconnectCB(ECS_DISCONNECT_CB DisconnectParamCB);
	void SetTimeouts(
		DWORD dwWinHttpOptionConnectRetriesParam,
		DWORD dwWinHttpOptionConnectTimeoutParam,
		DWORD dwWinHttpOptionReceiveResponseTimeoutParam,
		DWORD dwWinHttpOptionReceiveTimeoutParam,
		DWORD dwWinHttpOptionSendTimeoutParam,
		DWORD dwBadIPAddrAge);
	CString GetHost(void) const;
	void SetMaxWriteRequest(DWORD dwMaxWriteRequestParam);
	static void SetMaxWriteRequestAll(DWORD dwMaxWriteRequestParam);
	void SetDisableSecureLog(bool bDisable = true);
	void GetCertInfo(ECS_CERT_INFO& Rec);
	void SetSaveCertInfo(bool bSave);
	DWORD GetSecureError(void);
	static void RemoveACLDups(std::deque<CECSConnection::ACL_ENTRY>& UserAcls);
	bool IfValidMetadataTag(LPCTSTR pszMDString);
	static void GarbageCollect(void);
	bool TestAbort(void);
	static bool ValidateS3BucketName(LPCTSTR pszBucketName);
	void SetHTTPSecurityFlags(DWORD dwHTTPSecurityFlagsParam);
	DWORD RetrieveServerCertificate(ECS_CERT_INFO& CertInfo);
	static CString DumpBadIPMap(void);

	S3_ERROR SendRequest(LPCTSTR pszMethod, LPCTSTR pszResource, const void *pData, DWORD dwDataLen, CBuffer& RetData, std::list<HEADER_REQ> *pHeaderReq = nullptr, DWORD dwReceivedDataHint = 0, DWORD dwBufOffset = 0, STREAM_CONTEXT *pStreamSend = nullptr, STREAM_CONTEXT *pStreamReceive = nullptr, ULONGLONG ullTotalLen = 0ULL);

	S3_ERROR Create(LPCTSTR pszPath, const void *pData = nullptr, DWORD dwLen = 0, const std::list<HEADER_STRUCT> *pMDList = nullptr, const CBuffer *pChecksum = nullptr, STREAM_CONTEXT *pStreamSend = nullptr, ULONGLONG ullTotalLen = 0ULL, LPCTSTR pIfNoneMatch = nullptr, std::list<HEADER_REQ> *pReq = nullptr);
	S3_ERROR DeleteS3(LPCTSTR pszPath, LPCTSTR pszVersionId = nullptr);
	S3_ERROR DeleteS3(const std::list<S3_DELETE_ENTRY>& PathList);
	S3_ERROR Read(LPCTSTR pszPath, ULONGLONG lwLen, ULONGLONG lwOffset, CBuffer& RetData, DWORD dwBufOffset = 0, STREAM_CONTEXT *pStreamReceive = nullptr, std::list<HEADER_REQ> *pRcvHeaders = nullptr, ULONGLONG *pullReturnedLength = nullptr);
	S3_ERROR DirListing(LPCTSTR pszPath, DirEntryList_t& DirList, bool bSingle = false, LPCTSTR pszObjName = nullptr, LISTING_NEXT_MARKER_CONTEXT *pNextRequestMarker = nullptr, TCHAR cDelimiter = _T('/'));
	S3_ERROR DirListingS3Versions(LPCTSTR pszPath, DirEntryList_t& DirList, LPCTSTR pszObjName = nullptr, LISTING_NEXT_MARKER_CONTEXT *pNextRequestMarker = nullptr, TCHAR cDelimiter = _T('/'));
	S3_ERROR S3ServiceInformation(S3_SERVICE_INFO& ServiceInfo);
	void WriteMetadataEntry(std::list<HEADER_STRUCT>& MDList, LPCTSTR pszTag, const CBuffer& Data);
	void WriteMetadataEntry(std::list<HEADER_STRUCT>& MDList, LPCTSTR pszTag, const CString& sStr);
	S3_ERROR UpdateMetadata(LPCTSTR pszPath, const std::list<HEADER_STRUCT>& MDList, const std::list<CString> *pDeleteTagParam = nullptr);
	S3_ERROR ReadProperties(LPCTSTR pszPath, S3_SYSTEM_METADATA& Properties, LPCTSTR pszVersionId = nullptr, std::list<HEADER_STRUCT> *pMDList = nullptr, std::list<HEADER_REQ> *pReq = nullptr);
	S3_ERROR ReadACL(LPCTSTR pszPath, std::deque<ACL_ENTRY>& Acls, LPCTSTR pszVersion = nullptr);
	S3_ERROR WriteACL(LPCTSTR pszPath, const std::deque<ACL_ENTRY>& Acls, LPCTSTR pszVersion = nullptr);
	CString GenerateShareableURL(LPCTSTR pszPath, SYSTEMTIME *pstExpire);
	S3_ERROR CreateS3Bucket(LPCTSTR pszBucketName, const S3_BUCKET_OPTIONS *pOptions = nullptr, const std::list<CECSConnection::HEADER_STRUCT> *pMDList = nullptr);
	S3_ERROR DeleteS3Bucket(LPCTSTR pszBucketName);
	S3_ERROR S3GetBucketVersioning(LPCTSTR pszBucket, E_S3_VERSIONING& Versioning);
	S3_ERROR S3PutBucketVersioning(LPCTSTR pszBucket, E_S3_VERSIONING Versioning);
	S3_ERROR RenameS3(LPCTSTR pszOldPath, LPCTSTR pszNewPath, LPCTSTR pszVersionId, bool bCopy, const std::list<CECSConnection::HEADER_STRUCT> *pMDList, const std::list<CString> *pDeleteTagParam = nullptr);
	S3_ERROR DataNodeEndpointS3(S3_ENDPOINT_INFO& Endpoint);
	S3_ERROR GetObjectLockConfiguration(LPCTSTR pszBucket, S3_OBJ_LOCK_CONFIG& LockInfo);
	S3_ERROR S3GetLifecycle(LPCTSTR pszBucket, S3_LIFECYCLE_INFO& Lifecycle);
	S3_ERROR S3PutLifecycle(LPCTSTR pszBucket, const S3_LIFECYCLE_INFO& Lifecycle);
	S3_ERROR S3DeleteLifecycle(LPCTSTR pszBucket);
	S3_ERROR S3GetReplicationInfo(LPCTSTR pszPath, S3_REPLICATION_INFO& RepInfo);

	// S3 multipart upload support
	S3_ERROR S3MultiPartInitiate(LPCTSTR pszPath, S3_UPLOAD_PART_INFO& MultiPartInfo, const std::list<HEADER_STRUCT> *pMDList);
	S3_ERROR S3MultiPartUpload(const S3_UPLOAD_PART_INFO& MultiPartInfo, S3_UPLOAD_PART_ENTRY& PartEntry, STREAM_CONTEXT *pStreamSend, ULONGLONG ullTotalLen, LPCTSTR pszCopySource, ULONGLONG ullStartRange, LPCTSTR pszVersionId);
	S3_ERROR S3MultiPartComplete(const S3_UPLOAD_PART_INFO& MultiPartInfo, const std::list<std::shared_ptr<S3_UPLOAD_PART_ENTRY>>& PartList, S3_MPU_COMPLETE_INFO& MPUCompleteInfo);
	S3_ERROR S3MultiPartAbort(const S3_UPLOAD_PART_INFO& MultiPartInfo);
	S3_ERROR S3MultiPartList(LPCTSTR pszBucketName, S3_LIST_MULTIPART_UPLOADS& MultiPartList);

	// ECS Admin functions
	S3_ERROR ECSAdminLogin(LPCTSTR pszUser, LPCTSTR pszPassword);
	S3_ERROR ECSAdminLogout(void);
	S3_ERROR ECSAdminGetUserList(std::list<S3_ADMIN_USER_INFO>& UserList);
	S3_ERROR ECSAdminCreateUser(S3_ADMIN_USER_INFO& User);
	S3_ERROR ECSAdminGetKeysForUser(LPCTSTR pszUser, LPCTSTR pszNamespace, S3_ADMIN_USER_KEY_INFO& Keys);
	S3_ERROR ECSAdminCreateKeyForUser(S3_ADMIN_USER_INFO& User);
	S3_ERROR ECSAdminBillingBucket(_In_ const CString& sNamespace, _In_ const CString& sBucket, _Out_ ECS_BILLING_BUCKET& BucketInfo);
	S3_ERROR ECSAdminCapacity(_Out_ ECS_CAPACITY& CapacityInfo);
	S3_ERROR ECSAdminBucketInfo(_In_ const CString& sNamespace, _In_ const CString& sBucket, _Out_ ECS_BUCKET_INFO& BucketInfo);

	// ECS metadata search functions
	S3_ERROR S3GetMDSearchFields(S3_METADATA_SEARCH_FIELDS& MDFields);
	S3_ERROR S3GetMDSearchFields(LPCTSTR pszBucket, S3_METADATA_SEARCH_FIELDS_BUCKET& MDFieldBucket);
	S3_ERROR S3SearchMD(const S3_METADATA_SEARCH_PARAMS& Params, S3_METADATA_SEARCH_RESULT& MDSearchResult);

	// DT Query
	S3_ERROR ECSDTQuery(LPCTSTR pszNamespace, LPCTSTR pszBucket, LPCTSTR pszObject, bool bShowValue, LPCTSTR pszRandom, DT_QUERY_RESPONSE& Response);

	static DWORD MaxMetadataBinarySize(void);

	class CStateReserve
	{
	private:
		CStateRef State;
	public:
		CStateReserve(CECSConnection* pConn = nullptr)
			: State(pConn)
		{}
	};
};

ECSUTIL_EXT_API extern std::wostream& operator<<(std::wostream& os, const CECSConnection::S3_SYSTEM_METADATA& Rec);

class ECSUTIL_EXT_CLASS CECSConnectionAbortBase
{
private:
	const bool *pbAbort;			// pointer to abort bool
	bool bAbortIfTrue;				// determines sense of pbAbort
	CECSConnection *pHost;
	static bool IfShutdownCommon(void *pContext);

protected:
	virtual bool IfShutdown(void) = 0;

public:
	CECSConnectionAbortBase(CECSConnection *pHostParam = nullptr, const bool *pbAbortParam = nullptr, bool bAbortIfTrueParam = true)
	{
		pbAbort = pbAbortParam;
		bAbortIfTrue = bAbortIfTrueParam;
		pHost = pHostParam;
		if (pHost != nullptr)
		{
			if (pbAbort != nullptr)
				pHost->RegisterAbortPtr(pbAbort, bAbortIfTrue);
			pHost->RegisterShutdownCB(&CECSConnectionAbortBase::IfShutdownCommon, this);
		}
	}
	virtual ~CECSConnectionAbortBase()
	{
		try
		{
			if (pHost != nullptr)
			{
				if (pbAbort != nullptr)
					pHost->UnregisterAbortPtr(pbAbort);
				pHost->UnregisterShutdownCB(&CECSConnectionAbortBase::IfShutdownCommon, this);
			}
			pbAbort = nullptr;
			pHost = nullptr;
		}
		catch (const std::bad_array_new_length& E)
		{
			std::ignore = E;
		}
	}
};

} // end namespace ecs_sdk
